// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCXIiZGF60mSyWa-2CYvVhEGp5cyqJo0E',
    appId: '1:1009095169052:ios:9f3aa6f7d693dbd5907bd9',
    messagingSenderId: '1009095169052',
    projectId: 'fir-denetim-c6abc',
    iosBundleId: 'com.denetim.app.denetimApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCXIiZGF60mSyWa-2CYvVhEGp5cyqJo0E',
    appId: '1:1009095169052:ios:9f3aa6f7d693dbd5907bd9',
    messagingSenderId: '1009095169052',
    projectId: 'fir-denetim-c6abc',
    iosBundleId: 'com.denetim.app.denetimApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA34MWjv-08j5T5hlMhGPV2HzZo9kSqY8g',
    appId: '1:1009095169052:web:ac551e94b618a222907bd9',
    messagingSenderId: '1009095169052',
    projectId: 'fir-denetim-c6abc',
    authDomain: 'fir-denetim-c6abc.firebaseapp.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA34MWjv-08j5T5hlMhGPV2HzZo9kSqY8g',
    appId: '1:1009095169052:web:ac551e94b618a222907bd9',
    messagingSenderId: '1009095169052',
    projectId: 'fir-denetim-c6abc',
    authDomain: 'fir-denetim-c6abc.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3QKNGPhk8YKnVKiCszPCZRuB8xxexYBY',
    appId: '1:1009095169052:android:64a1c784d7ccbca8907bd9',
    messagingSenderId: '1009095169052',
    projectId: 'fir-denetim-c6abc',
  );

}
